Repository PilotDataPlatform/helm-charts, pull requests merged in 2024-05, with the labels that each got.

#70 PILOT-5066: Workflow Manager - 2.2.1 Doesn't send out completed email on completed workflows.
  workflow-manager/Chart.yaml
  workflow-manager/templates/clusterrole.yaml
Labels: bug

#71 PILOT-5114: Add virtual machines to workspace cluster role
  .gitignore
  workspace-service/templates/clusterrole.yaml
Labels: enhancement

#72 PILOT-5114: Update workspace service chart version
  workspace-service/Chart.yaml
Labels: enhancement

#77 PILOT-5224 Add permissions to Workspace service
  docs/index.yaml
  docs/workspace-service-1.2.8.tgz
  workspace-service/Chart.yaml
  workspace-service/templates/clusterrole.yaml
Labels: bug, enhancement

#78 PILOT-5274: Add guacamole and postgres operator resources
  docs/guacamole-operator-0.1.2.tgz
  docs/index.yaml
  docs/postgresql-operator-0.1.2.tgz
  guacamole-operator/Chart.yaml
  guacamole-operator/templates/stable.indocpilot.io_guacamoles.yaml
  postgresql-operator/Chart.yaml
  postgresql-operator/templates/stable.indocpilot.io_postgresqls.yaml
Labels: enhancement
